# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-09-18 23:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('srt_app', '0002_auto_20190918_2340'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Show',
            new_name='Shows',
        ),
    ]
