# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-09-18 23:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('srt_app', '0003_auto_20190918_2341'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shows',
            old_name='decription',
            new_name='description',
        ),
    ]
