# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-09-19 16:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('srt_app', '0004_auto_20190918_2350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shows',
            name='release_date',
            field=models.DateField(verbose_name='%Y-%m-%d'),
        ),
    ]
